version: '3.7'

services:
  postfix:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAILNAME=${MAILNAME}
        - SMTP_USER=${SMTP_USER}
        - EMAIL_FROM=${EMAIL_FROM}
        - EMAIL_TO=${EMAIL_TO}
    container_name: postfix
    env_file:
      - .env
    networks:
      - email-network
    ports:
      - "25:25"
      - "587:587"

networks:
  email-network:
    external: true
